# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20181023_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particiant',
            name='participant_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='particiant',
            index=models.Index(fields=['participant_id', 'name'], name='scheduler_p_partici_45dcfd_idx'),
        ),
    ]
