# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20181023_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Particiant',
            new_name='Participant',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='scheduler_p_partici_45dcfd_idx',
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['participant_id', 'name'], name='scheduler_p_partici_1e7152_idx'),
        ),
    ]
