# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_schedule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['meeting_notes'], name='scheduler_s_meeting_c25d0c_idx'),
        ),
    ]
